args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", args, value = TRUE)
this <- normalizePath(sub("^--file=", "", file_arg[[1]]), winslash = "/")
root <- normalizePath(file.path(dirname(this), ".."), winslash = "/")
source(file.path(root, "skill", "reproduce-scrna-study", "scripts", "common.R"))
cfg <- load_config(file.path(root, "examples", "GSE131736", "config.yaml"))
meta <- validate_config(cfg, require_data = FALSE)
stopifnot(nrow(meta) == 9)
stopifnot(identical(sort(meta$day[meta$cohort == "H9_core"]), c(0L, 4L, 6L, 8L)))
stopifnot(identical(sort(meta$day[meta$cohort == "H9_late"]), c(8L, 12L)))
cat("Configuration smoke test passed.\n")
